### ISSUE TITLE
Migrate plugin plugin.keychain

### ISSUE THREAD

**Issue by ricaragao** [solar2d/plugins.solar2d.com#21]
Migrate the plugin: plugin.keychain 
publisherId = "us.datalabs"

**Comment by Shchvova** [comment]
Sorry, I don't see `plugin.keychain`. Is this a new plugin you wish to create?

**Comment by ricaragao** [comment]
@Shchvova , no it is an old plugin from Corona. It was published in the Corona plugins portal.

**Comment by Shchvova** [comment]
Oh... I would need author's permission to publish it then. I will try to get it.

**Comment by ricaragao** [comment]
Great. I talked with him. Let me know if you need help to contact him.

**Comment by Shchvova** [comment]
Absolutely! Ask him to email me (`vlad`) either at coronalabs.com or solar2d.com. I am gladly bringing old or new plugins to this repository.

**Comment by Shchvova** [comment]
Done!
