### ISSUE TITLE
com.cabagomez-plugin.bugsnag

### ISSUE THREAD

**Issue by agramonte** [solar2d/plugins.solar2d.com#54]
### Plugin description

Implementation of [https://www.bugsnag.com/](Bugsnag).

Plugin located here:
https://github.com/agramonte/com.cabagomez-plugin.bugsnag

### Desired publisher Id

com.cabagomez

### Your plugin name

plugin.bugsnag

### Terms and conditions

- [X] If I receive invitation to the new repo I will read and follow the README in it, and would not abuse the automation

**Comment by Shchvova** [comment]
So now new repo would be created and when you push binaries to it will get everything done automatically
